### PR TITLE
Rubocop / code style cleanups

### PR DESCRIPTION
**Pull request by lacostej**

### CODE REVIEW

**Comment by KrauseFx** [comment]
It looks like it's not the same `rubocop` config we use in the other repos. Do you have an idea how to best sync the style config across repositories?

**Comment by lacostej** [comment]
> It looks like it's not the same rubocop config we use in the other repos. 

I used the one from fastlane_core, I wasn't sure which one to use

> Do you have an idea how to best sync the style config across repositories?

different ideas. It depends if you have other things you want to sync.

Maybe something like

* a repo for all the shared configs.

  fastlane_common_config.git/common-config/rubocop.yml

* a way to share these files into each project. I would use gitsubmodules to include common-config directory into all projects.

* then modify the .rubocop.yml to inherit from common-config/rubocop.yml in each project

* an optional shortcut to update the Maybe use a rake or fastlane task to do the git submodule update.

You can also replace the git submodule with a simple ruby script to download from github. I would go for git submodule I think.

**Comment by KrauseFx** [comment]
@lacostej I'm solving this problem right now, already started a new thing `countdown` :+1:

**Comment by KrauseFx** [comment]
Thanks for the pull request :+1:

**Pull request merged**
