### PR TITLE
Display and output formatting

### PR DESCRIPTION
**Pull request by lacostej**
This is a PR for #8 and #9. Please review and comment on the following:

* code style (I believe I addressed the early comments)
* api stability
 * whether it was acceptable to rename Codes::CodesRunner.run (I believe so)
 * whether it was acceptable to remove the :urls argument to Codes::CodesRunner.run
 * whether we want to keep the --url argument or not from the CLI (I would scrap it, and also from the README)
* documentation
 * should the --format documentation include other data (I took it from my own product)
 * whether the documentation should describe further the format options %c, %d, etc
* functionality
 * as for the new display command, I have duplicated a few things with the download one, and there are things that could be removed (e.g. do we really need to create an output file, if yes, what should be its name) ? 

When we have addressed everything, I will rebase / squash everything before you can merge.

### CODE REVIEW

**Comment by lacostej** [comment]
Would have loved to see that one in the latest release :)

**Comment by lacostej** [comment]
@KrauseFx should we look into merging this at some point ?

**Comment by KrauseFx** [comment]
Sorry for the delay, I'll take a look at this today! :+1:

**Comment by lacostej** [comment]
I updated to latest HEAD + added support for the new country parameter.

Code is now ready for review. 

Maybe we don't need to append information about remaining codes to a file in the display method.

**Comment by KrauseFx** [comment]
Looks great, thank you so much for the pull request. Sorry it took so long for me to review it.

**Comment by lacostej** [comment]
@KrauseFx  no problem

**Pull request merged**
